name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none
      - run: composer validate --strict
      - run: composer update --prefer-dist --no-interaction
      - run: composer check-platform-reqs

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none
      - run: composer update --prefer-dist --no-interaction
      - run: composer test

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none
      - run: composer update --prefer-dist --no-interaction
      - run: composer format

  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none
      - run: composer update --prefer-dist --no-interaction
      - run: composer analyse
